# DAV 5400 Module 10 Assignment

- Importing the __pandas__ dataframe
- Raw file github link: https://raw.githubusercontent.com/Nikkat-Afrin/DAV-5400/master/M10_Data.csv
- Reading the csv data by using __read_csv__ function.

In [197]:
import pandas as pd
data= pd.read_csv("https://raw.githubusercontent.com/Nikkat-Afrin/DAV-5400/master/M10_Data.csv")
data

   Month     Category      Caltex        Gulf       Mobil
0   Open   Engine Oil  140 :  000  199 :  000  141 :  000
1    NaN  GearBox Oil  198 :  000  132 :  000  121 :  000
2    Jan   Engine Oil  170 :  103  194 :  132  109 :  127
3    NaN  GearBox Oil  132 :  106  125 :  105  191 :  100
4    Feb   Engine Oil  112 :  133  138 :  113  171 :  101
5    NaN  GearBox Oil  193 :  148  199 :  119  134 :  127
6    Mar   Engine Oil  184 :  100  141 :  141  114 :  108
7    NaN  GearBox Oil  138 :  121  172 :  133  193 :  115
8    Apr   Engine Oil  149 :  150  117 :  118  117 :  118
9    NaN  GearBox Oil  185 :  125  191 :  133  119 :  121
10   May   Engine Oil  170 :  139  104 :  119  200 :  117
11   NaN  GearBox Oil  168 :  117  138 :  102  121 :  146
12   Jun   Engine Oil  159 :  129  170 :  138  169 :  105
13   NaN  GearBox Oil  107 :  129  195 :  141  141 :  112

## Task 1:

### __Step 1__: Apply appropriate column heading to the second column

In [198]:
# rename the columns 
data.rename( columns={'Category':'Oil_type'}, inplace=True )
data

   Month     Oil_type      Caltex        Gulf       Mobil
0   Open   Engine Oil  140 :  000  199 :  000  141 :  000
1    NaN  GearBox Oil  198 :  000  132 :  000  121 :  000
2    Jan   Engine Oil  170 :  103  194 :  132  109 :  127
3    NaN  GearBox Oil  132 :  106  125 :  105  191 :  100
4    Feb   Engine Oil  112 :  133  138 :  113  171 :  101
5    NaN  GearBox Oil  193 :  148  199 :  119  134 :  127
6    Mar   Engine Oil  184 :  100  141 :  141  114 :  108
7    NaN  GearBox Oil  138 :  121  172 :  133  193 :  115
8    Apr   Engine Oil  149 :  150  117 :  118  117 :  118
9    NaN  GearBox Oil  185 :  125  191 :  133  119 :  121
10   May   Engine Oil  170 :  139  104 :  119  200 :  117
11   NaN  GearBox Oil  168 :  117  138 :  102  121 :  146
12   Jun   Engine Oil  159 :  129  170 :  138  169 :  105
13   NaN  GearBox Oil  107 :  129  195 :  141  141 :  112

###  __Step 2__: Now the __pd.melt()__ function can be used to convert the table from __wide__ to __long format__.

- Note the use of the __id_vars__ and __value_vars__ parameters


- Also note that we are defining the name of a new column to store the Oil suppliers names: '__OIl_suppliers__'


- And the new columns that will store the number of gallons of oil purchased and consumed for each month is labeled as '__Purchased__' and '__Consumed__'.

In [199]:
# Melting from wide to long format, first 2 columns are used to 
ids = ["Month","Oil_type"]

# the remaining columns are treated as data values to be pivoted into long format
values = data.columns[2:]

# use pd.melt() to convert the wide table to long format
# Note the use of the id_vars and value_vars parameters
# also note that we are defining the name of a new column to store the city names: 'City'
# while the new column that will store the frequency counts of on time / departed flights
# is labeled as 'Value'

data = pd.melt(frame=data, id_vars=ids, value_vars=values, var_name='Oil_suppliers', value_name='Value')

data

   Month     Oil_type Oil_suppliers       Value
0   Open   Engine Oil        Caltex  140 :  000
1    NaN  GearBox Oil        Caltex  198 :  000
2    Jan   Engine Oil        Caltex  170 :  103
3    NaN  GearBox Oil        Caltex  132 :  106
4    Feb   Engine Oil        Caltex  112 :  133
5    NaN  GearBox Oil        Caltex  193 :  148
6    Mar   Engine Oil        Caltex  184 :  100
7    NaN  GearBox Oil        Caltex  138 :  121
8    Apr   Engine Oil        Caltex  149 :  150
9    NaN  GearBox Oil        Caltex  185 :  125
10   May   Engine Oil        Caltex  170 :  139
11   NaN  GearBox Oil        Caltex  168 :  117
12   Jun   Engine Oil        Caltex  159 :  129
13   NaN  GearBox Oil        Caltex  107 :  129
14  Open   Engine Oil          Gulf  199 :  000
15   NaN  GearBox Oil          Gulf  132 :  000
16   Jan   Engine Oil          Gulf  194 :  132
17   NaN  GearBox Oil          Gulf  125 :  105
18   Feb   Engine Oil          Gulf  138 :  113
19   NaN  GearBox Oil          Gulf  199 :  119
20   Mar   Engine Oil          Gulf  141 :  141
21   NaN  GearBox Oil          Gulf  172 :  133
22   Apr   Engine Oil          Gulf  117 :  118
23   NaN  GearBox Oil          Gulf  191 :  133
24   May   Engine Oil          Gulf  104 :  119
25   NaN  GearBox Oil          Gulf  138 :  102
26   Jun   Engine Oil          Gulf  170 :  138
27   NaN  GearBox Oil          Gulf  195 :  141
28  Open   Engine Oil         Mobil  141 :  000
29   NaN  GearBox Oil         Mobil  121 :  000
30   Jan   Engine Oil         Mobil  109 :  127
31   NaN  GearBox Oil         Mobil  191 :  100
32   Feb   Engine Oil         Mobil  171 :  101
33   NaN  GearBox Oil         Mobil  134 :  127
34   Mar   Engine Oil         Mobil  114 :  108
35   NaN  GearBox Oil         Mobil  193 :  115
36   Apr   Engine Oil         Mobil  117 :  118
37   NaN  GearBox Oil         Mobil  119 :  121
38   May   Engine Oil         Mobil  200 :  117
39   NaN  GearBox Oil         Mobil  121 :  146
40   Jun   Engine Oil         Mobil  169 :  105
41   NaN  GearBox Oil         Mobil  141 :  112

We now have the data set in long format. 
But we still have a data problem:

- We have many 'NaN' values in the '__Month__' column as a result of the __melt()__ operation

### __Step 3__: Correctly fill the NaN items in the 'Month' column

- Based on the content of the original data frame, it appears that the 'NaN' values in the 'Month' column should be filled with the 'Month' value from the preceding row. We can use the 'forward fill' method within the __fillna()__ function to do this:

In [200]:
data['Month'].fillna(method='ffill', inplace = True)
data

   Month     Oil_type Oil_suppliers       Value
0   Open   Engine Oil        Caltex  140 :  000
1   Open  GearBox Oil        Caltex  198 :  000
2    Jan   Engine Oil        Caltex  170 :  103
3    Jan  GearBox Oil        Caltex  132 :  106
4    Feb   Engine Oil        Caltex  112 :  133
5    Feb  GearBox Oil        Caltex  193 :  148
6    Mar   Engine Oil        Caltex  184 :  100
7    Mar  GearBox Oil        Caltex  138 :  121
8    Apr   Engine Oil        Caltex  149 :  150
9    Apr  GearBox Oil        Caltex  185 :  125
10   May   Engine Oil        Caltex  170 :  139
11   May  GearBox Oil        Caltex  168 :  117
12   Jun   Engine Oil        Caltex  159 :  129
13   Jun  GearBox Oil        Caltex  107 :  129
14  Open   Engine Oil          Gulf  199 :  000
15  Open  GearBox Oil          Gulf  132 :  000
16   Jan   Engine Oil          Gulf  194 :  132
17   Jan  GearBox Oil          Gulf  125 :  105
18   Feb   Engine Oil          Gulf  138 :  113
19   Feb  GearBox Oil          Gulf  199 :  119
20   Mar   Engine Oil          Gulf  141 :  141
21   Mar  GearBox Oil          Gulf  172 :  133
22   Apr   Engine Oil          Gulf  117 :  118
23   Apr  GearBox Oil          Gulf  191 :  133
24   May   Engine Oil          Gulf  104 :  119
25   May  GearBox Oil          Gulf  138 :  102
26   Jun   Engine Oil          Gulf  170 :  138
27   Jun  GearBox Oil          Gulf  195 :  141
28  Open   Engine Oil         Mobil  141 :  000
29  Open  GearBox Oil         Mobil  121 :  000
30   Jan   Engine Oil         Mobil  109 :  127
31   Jan  GearBox Oil         Mobil  191 :  100
32   Feb   Engine Oil         Mobil  171 :  101
33   Feb  GearBox Oil         Mobil  134 :  127
34   Mar   Engine Oil         Mobil  114 :  108
35   Mar  GearBox Oil         Mobil  193 :  115
36   Apr   Engine Oil         Mobil  117 :  118
37   Apr  GearBox Oil         Mobil  119 :  121
38   May   Engine Oil         Mobil  200 :  117
39   May  GearBox Oil         Mobil  121 :  146
40   Jun   Engine Oil         Mobil  169 :  105
41   Jun  GearBox Oil         Mobil  141 :  112

In [201]:
data['Value']

0     140 :  000
1     198 :  000
2     170 :  103
3     132 :  106
4     112 :  133
5     193 :  148
6     184 :  100
7     138 :  121
8     149 :  150
9     185 :  125
10    170 :  139
11    168 :  117
12    159 :  129
13    107 :  129
14    199 :  000
15    132 :  000
16    194 :  132
17    125 :  105
18    138 :  113
19    199 :  119
20    141 :  141
21    172 :  133
22    117 :  118
23    191 :  133
24    104 :  119
25    138 :  102
26    170 :  138
27    195 :  141
28    141 :  000
29    121 :  000
30    109 :  127
31    191 :  100
32    171 :  101
33    134 :  127
34    114 :  108
35    193 :  115
36    117 :  118
37    119 :  121
38    200 :  117
39    121 :  146
40    169 :  105
41    141 :  112
Name: Value, dtype: object

In [202]:
# Splitting the 'Value' column into two columns
data[['Purchased', 'Consumed']] = data['Value'].str.split(':', expand=True)
# Dropping the original 'Value' column
data.drop(columns=['Value'], inplace=True)
data

   Month     Oil_type Oil_suppliers Purchased Consumed
0   Open   Engine Oil        Caltex      140       000
1   Open  GearBox Oil        Caltex      198       000
2    Jan   Engine Oil        Caltex      170       103
3    Jan  GearBox Oil        Caltex      132       106
4    Feb   Engine Oil        Caltex      112       133
5    Feb  GearBox Oil        Caltex      193       148
6    Mar   Engine Oil        Caltex      184       100
7    Mar  GearBox Oil        Caltex      138       121
8    Apr   Engine Oil        Caltex      149       150
9    Apr  GearBox Oil        Caltex      185       125
10   May   Engine Oil        Caltex      170       139
11   May  GearBox Oil        Caltex      168       117
12   Jun   Engine Oil        Caltex      159       129
13   Jun  GearBox Oil        Caltex      107       129
14  Open   Engine Oil          Gulf      199       000
15  Open  GearBox Oil          Gulf      132       000
16   Jan   Engine Oil          Gulf      194       132
17   Jan  GearBox Oil          Gulf      125       105
18   Feb   Engine Oil          Gulf      138       113
19   Feb  GearBox Oil          Gulf      199       119
20   Mar   Engine Oil          Gulf      141       141
21   Mar  GearBox Oil          Gulf      172       133
22   Apr   Engine Oil          Gulf      117       118
23   Apr  GearBox Oil          Gulf      191       133
24   May   Engine Oil          Gulf      104       119
25   May  GearBox Oil          Gulf      138       102
26   Jun   Engine Oil          Gulf      170       138
27   Jun  GearBox Oil          Gulf      195       141
28  Open   Engine Oil         Mobil      141       000
29  Open  GearBox Oil         Mobil      121       000
30   Jan   Engine Oil         Mobil      109       127
31   Jan  GearBox Oil         Mobil      191       100
32   Feb   Engine Oil         Mobil      171       101
33   Feb  GearBox Oil         Mobil      134       127
34   Mar   Engine Oil         Mobil      114       108
35   Mar  GearBox Oil         Mobil      193       115
36   Apr   Engine Oil         Mobil      117       118
37   Apr  GearBox Oil         Mobil      119       121
38   May   Engine Oil         Mobil      200       117
39   May  GearBox Oil         Mobil      121       146
40   Jun   Engine Oil         Mobil      169       105
41   Jun  GearBox Oil         Mobil      141       112

### The data is now in 'tidy' format:

- Each row is now comprised of a single observation (i.e., the Purchase of either a particular Oil supplier or Oil type of a particular month)

In [203]:
data.dtypes

Month            object
Oil_type         object
Oil_suppliers    object
Purchased        object
Consumed         object
dtype: object

In [204]:
# Convert Purchased and Consumed columns to numeric
data['Purchased'] = pd.to_numeric(data['Purchased'])
data['Consumed'] = pd.to_numeric(data['Consumed'])

print(data.dtypes)

Month            object
Oil_type         object
Oil_suppliers    object
Purchased         int64
Consumed          int64
dtype: object

## Task 2:

### Step1:

- Here I am trying to group by the data by the combination of "Oil_suppliers" and "Oil_type" columns. Then, this grouped data can be used to calculate the sum of the "Purchased" and "Consumed" columns for each group using the .agg() method.

In [205]:

# Group by Oil_suppliers and calculate the sum of Purchased and Consumed
grouped_data = data.groupby(["Oil_suppliers","Oil_type"]).agg({"Purchased": "sum", "Consumed": "sum"})

print(grouped_data)

                           Purchased  Consumed
Oil_suppliers Oil_type
Caltex        Engine Oil        1084       754
              GearBox Oil       1121       746
Gulf          Engine Oil        1063       761
              GearBox Oil       1152       733
Mobil         Engine Oil        1021       676
              GearBox Oil       1020       721

### Step 2:
- The Remaining column gives the amount of oil left after the consumption and it can be calculated by subtracting the Purchased column with the consumption column.

In [206]:
# Calculating the remaining oil with the help of Purchased and consumed column
grouped_data['Remaining'] = grouped_data['Purchased']-grouped_data['Consumed']

grouped_data

                           Purchased  Consumed  Remaining
Oil_suppliers Oil_type
Caltex        Engine Oil        1084       754        330
              GearBox Oil       1121       746        375
Gulf          Engine Oil        1063       761        302
              GearBox Oil       1152       733        419
Mobil         Engine Oil        1021       676        345
              GearBox Oil       1020       721        299

- The amount of oil remaining at the end of the chronological period for each pair of oil types/ brands can be seen in the Remaining column of the grouped_data data frame.

### Step 1: Question 2
- Here I am trying to group by the data by the combination of "Oil_suppliers" and "Oil_type" columns. Then, this grouped data can be used to calculate the sum of the "Consumed" columns for each group using the .agg() method.

In [207]:

# Group by Oil_suppliers and calculate the sum of Purchased and Consumed
group_data = data.groupby(["Oil_type","Oil_suppliers"]).agg({ "Consumed": "sum"})

group_data.reset_index(inplace=True)
group_data

      Oil_type Oil_suppliers  Consumed
0   Engine Oil        Caltex       754
1   Engine Oil          Gulf       761
2   Engine Oil         Mobil       676
3  GearBox Oil        Caltex       746
4  GearBox Oil          Gulf       733
5  GearBox Oil         Mobil       721

In [208]:
group_data.columns

Index(['Oil_type', 'Oil_suppliers', 'Consumed'], dtype='object')

### Step 2:
- To get the highest amount of the oil consumed in both the oil types im again using the group by function.

In [209]:
max_df = group_data.groupby(["Oil_type"]).agg({ "Consumed": "max"})
max_df.reset_index(inplace=True)
max_df

      Oil_type  Consumed
0   Engine Oil       761
1  GearBox Oil       746

### Step 3:
- With the help of __merge()__ i was try to apply __inner join__ on the oil_type and consumed to the group_data to also get which oil_suppliers consume the most amount of Oil.

In [210]:
final_df = pd.merge(group_data, max_df, how='inner', on=['Oil_type', 'Consumed'])
final_df

      Oil_type Oil_suppliers  Consumed
0   Engine Oil          Gulf       761
1  GearBox Oil        Caltex       746

At the end of the chronological period, the most consumed brand of oil for each of the two separate types of oil is __Gulf__ and __Caltex__.

## Task 3

- The __wide Format__ structure that is given to us is gives us the understandable visuals of the data but it is still not clear to us without any explanation.
- The issue mainly lies in the data of the columns __Caltex__,__Gulf__ and __Mobil__.
- In these columns we can see some statistical numbers such as __140:000__, if we are not given any context we cant make sense of these numbers.
- But we were given the description that the number that is displayed before the colon ':' is the Purchased number of gallons  of Oil and the number that is present after the ':' is the consumed number of gallons of OIl.
- So, I would definitely change my __long format__ data frame into __wide Format__ but i would __not mimic the original Structure__.

In [211]:
df= pd.read_csv("https://raw.githubusercontent.com/Nikkat-Afrin/DAV-5400/master/M10_Data.csv")
# The original wide format data frame 
df

   Month     Category      Caltex        Gulf       Mobil
0   Open   Engine Oil  140 :  000  199 :  000  141 :  000
1    NaN  GearBox Oil  198 :  000  132 :  000  121 :  000
2    Jan   Engine Oil  170 :  103  194 :  132  109 :  127
3    NaN  GearBox Oil  132 :  106  125 :  105  191 :  100
4    Feb   Engine Oil  112 :  133  138 :  113  171 :  101
5    NaN  GearBox Oil  193 :  148  199 :  119  134 :  127
6    Mar   Engine Oil  184 :  100  141 :  141  114 :  108
7    NaN  GearBox Oil  138 :  121  172 :  133  193 :  115
8    Apr   Engine Oil  149 :  150  117 :  118  117 :  118
9    NaN  GearBox Oil  185 :  125  191 :  133  119 :  121
10   May   Engine Oil  170 :  139  104 :  119  200 :  117
11   NaN  GearBox Oil  168 :  117  138 :  102  121 :  146
12   Jun   Engine Oil  159 :  129  170 :  138  169 :  105
13   NaN  GearBox Oil  107 :  129  195 :  141  141 :  112

In [212]:
# My long format data frame structure
data

   Month     Oil_type Oil_suppliers  Purchased  Consumed
0   Open   Engine Oil        Caltex        140         0
1   Open  GearBox Oil        Caltex        198         0
2    Jan   Engine Oil        Caltex        170       103
3    Jan  GearBox Oil        Caltex        132       106
4    Feb   Engine Oil        Caltex        112       133
5    Feb  GearBox Oil        Caltex        193       148
6    Mar   Engine Oil        Caltex        184       100
7    Mar  GearBox Oil        Caltex        138       121
8    Apr   Engine Oil        Caltex        149       150
9    Apr  GearBox Oil        Caltex        185       125
10   May   Engine Oil        Caltex        170       139
11   May  GearBox Oil        Caltex        168       117
12   Jun   Engine Oil        Caltex        159       129
13   Jun  GearBox Oil        Caltex        107       129
14  Open   Engine Oil          Gulf        199         0
15  Open  GearBox Oil          Gulf        132         0
16   Jan   Engine Oil          Gulf        194       132
17   Jan  GearBox Oil          Gulf        125       105
18   Feb   Engine Oil          Gulf        138       113
19   Feb  GearBox Oil          Gulf        199       119
20   Mar   Engine Oil          Gulf        141       141
21   Mar  GearBox Oil          Gulf        172       133
22   Apr   Engine Oil          Gulf        117       118
23   Apr  GearBox Oil          Gulf        191       133
24   May   Engine Oil          Gulf        104       119
25   May  GearBox Oil          Gulf        138       102
26   Jun   Engine Oil          Gulf        170       138
27   Jun  GearBox Oil          Gulf        195       141
28  Open   Engine Oil         Mobil        141         0
29  Open  GearBox Oil         Mobil        121         0
30   Jan   Engine Oil         Mobil        109       127
31   Jan  GearBox Oil         Mobil        191       100
32   Feb   Engine Oil         Mobil        171       101
33   Feb  GearBox Oil         Mobil        134       127
34   Mar   Engine Oil         Mobil        114       108
35   Mar  GearBox Oil         Mobil        193       115
36   Apr   Engine Oil         Mobil        117       118
37   Apr  GearBox Oil         Mobil        119       121
38   May   Engine Oil         Mobil        200       117
39   May  GearBox Oil         Mobil        121       146
40   Jun   Engine Oil         Mobil        169       105
41   Jun  GearBox Oil         Mobil        141       112

### Converting the long format into the wide format

- To convert the long format into the wide format im using the __pivot_table()__ function.This pivots the DataFrame data by specifying the row index as a multi-level index consisting of the columns "Month" and "Oil_type".

- The __columns__ parameter specifies the columns to be used for creating separate columns in the pivoted DataFrame, which are the unique values from the __Oil_suppliers__ column.

- The __values__ parameter indicates which columns' values will be used to fill the pivoted DataFrame. In this case, it includes both __Consumed__ and __Purchased__ columns.

-  After pivoting the DataFrame, __.reset_index()__ resets the index to make the columns "Month" and "Oil_type" regular columns again. The __inplace=True__ parameter ensures that the changes are made directly to the df_pivot DataFrame.

In [214]:
# Pivot the DataFrame
df_pivot = data.pivot_table(index=[ 'Month','Oil_type'], columns='Oil_suppliers', values=['Consumed', 'Purchased'])

# Reset the index to make 'Month' and 'Oil_type' normal columns again
df_pivot.reset_index(inplace=True)
df_pivot

              Month     Oil_type Consumed            Purchased
Oil_suppliers                      Caltex Gulf Mobil    Caltex Gulf Mobil
0               Apr   Engine Oil      150  118   118       149  117   117
1               Apr  GearBox Oil      125  133   121       185  191   119
2               Feb   Engine Oil      133  113   101       112  138   171
3               Feb  GearBox Oil      148  119   127       193  199   134
4               Jan   Engine Oil      103  132   127       170  194   109
5               Jan  GearBox Oil      106  105   100       132  125   191
6               Jun   Engine Oil      129  138   105       159  170   169
7               Jun  GearBox Oil      129  141   112       107  195   141
8               Mar   Engine Oil      100  141   108       184  141   114
9               Mar  GearBox Oil      121  133   115       138  172   193
10              May   Engine Oil      139  119   117       170  104   200
11              May  GearBox Oil      117  102   146       168  138   121
12             Open   Engine Oil        0    0     0       140  199   141
13             Open  GearBox Oil        0    0     0       198  132   121

As we can see above that we got our desired wide format but there is still a major problem in the data frame that is the month column is not in a ordered format for this we have to catrgorize the month column and then we should set the order and perform the same processes which we are doing in the above to convert it into the wide_format.

In [216]:
# Define the order of the months
month_order = ['Open', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Convert 'Month' to a categorical type with the categories ordered
data['Month'] = pd.Categorical(data['Month'], categories=month_order, ordered=True)

# Pivot the DataFrame
data_pivot = data.pivot_table(index=['Month', 'Oil_type'], columns='Oil_suppliers', values=['Purchased', 'Consumed'])

# Reset the index to make 'Month' and 'Oil_type' normal columns again
data_pivot.reset_index(inplace=True)

data_pivot

              Month     Oil_type Consumed            Purchased
Oil_suppliers                      Caltex Gulf Mobil    Caltex Gulf Mobil
0              Open   Engine Oil        0    0     0       140  199   141
1              Open  GearBox Oil        0    0     0       198  132   121
2               Jan   Engine Oil      103  132   127       170  194   109
3               Jan  GearBox Oil      106  105   100       132  125   191
4               Feb   Engine Oil      133  113   101       112  138   171
5               Feb  GearBox Oil      148  119   127       193  199   134
6               Mar   Engine Oil      100  141   108       184  141   114
7               Mar  GearBox Oil      121  133   115       138  172   193
8               Apr   Engine Oil      150  118   118       149  117   117
9               Apr  GearBox Oil      125  133   121       185  191   119
10              May   Engine Oil      139  119   117       170  104   200
11              May  GearBox Oil      117  102   146       168  138   121
12              Jun   Engine Oil      129  138   105       159  170   169
13              Jun  GearBox Oil      129  141   112       107  195   141

In [217]:
data_pivot.columns

MultiIndex([(    'Month',       ''),
            ( 'Oil_type',       ''),
            ( 'Consumed', 'Caltex'),
            ( 'Consumed',   'Gulf'),
            ( 'Consumed',  'Mobil'),
            ('Purchased', 'Caltex'),
            ('Purchased',   'Gulf'),
            ('Purchased',  'Mobil')],
           names=[None, 'Oil_suppliers'])

Here we are trying to change the columns of the purchased and consumed columns by using the __.reindex()__ method.

In [218]:
# Assuming df is your DataFrame and you want to move the 'Purchased' columns before the 'Consumed' columns
new_columns_order = [('Month', ''), ('Oil_type', ''), 
                     ('Purchased', 'Caltex'), ('Purchased', 'Gulf'), ('Purchased', 'Mobil'), 
                     ('Consumed', 'Caltex'), ('Consumed', 'Gulf'), ('Consumed', 'Mobil')]

data_pivot = data_pivot.reindex(new_columns_order, axis=1)

In [195]:
data_pivot

              Month     Oil_type Purchased            Consumed
Oil_suppliers                       Caltex Gulf Mobil   Caltex Gulf Mobil
0              Open   Engine Oil       140  199   141        0    0     0
1              Open  GearBox Oil       198  132   121        0    0     0
2               Jan   Engine Oil       170  194   109      103  132   127
3               Jan  GearBox Oil       132  125   191      106  105   100
4               Feb   Engine Oil       112  138   171      133  113   101
5               Feb  GearBox Oil       193  199   134      148  119   127
6               Mar   Engine Oil       184  141   114      100  141   108
7               Mar  GearBox Oil       138  172   193      121  133   115
8               Apr   Engine Oil       149  117   117      150  118   118
9               Apr  GearBox Oil       185  191   119      125  133   121
10              May   Engine Oil       170  104   200      139  119   117
11              May  GearBox Oil       168  138   121      117  102   146
12              Jun   Engine Oil       159  170   169      129  138   105
13              Jun  GearBox Oil       107  195   141      129  141   112

Hence, According to me the above wide structure will be easy to understand from the visual point of view.

### Thank you